Project setup
ouasamine/hello-microverse pull request #2
Opened 2022-08-16 15:46 UTC by ouasamine

2022-08-16 16:31 UTC, BenMukebo requested changes
### Hi @ouasamine,

You did a great job so far 👏🏼 👏🏼
There are some issues that you still need to work on to go to the next project but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

### To highlight 💪🏻

- [HTML and CSS](https://github.com/microverseinc/linters-config) linter has been set up correctly ✔️   
- Github flow was correctly used.  ✔️    
- There is a .gitignore file listing test.md file and node_modules directory.  ✔️ 
 👍  Good job!


## STATUS: CHANGES REQUESTED  ♻️ 
_Please Check the comments under the review and make all required changes_

- [x] Please, Write a meaningful title for your pull request and always add a short summary of changes introduced in the pull request. you can check the  [Professional repo - basic rules](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/documentation/articles/professional_repo_rules.md#:~:text=basic%20rules%20to%20follow%20in%20Microverse%20projects)
eg: 
```
## In this Milestone, I have done the following step to set up a "Hello world" repository:

- [ ] Create a new GitHub repo.
- [ ] Add a `.gitignore` file.
- [ ] Set up [a linter for HTML and CSS](https://github.com/microverseinc/linters-config).
- [ ] Make sure that any files that are not relevant are ignored by git.
- [ ] Add descriptive README file .....

```

- [ ] Great job on adding linters to your project👏 . However, they are not passing yet Linter result should be green, kindly fix this issue it is always better to have all linter checks passing, this helps you avoid errors and enforces conventions.

- [x] Kindly remove the empty `a` file added from in the root directory of this project 👎🏻 



## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

- [OPTIONAL ] Kindly, make to use descriptive commit messages. Each commit message should be written in the imperative tense and always `capitalized`. [Read more about how to write descriptive commit messages](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/documentation/articles/professional_repo_rules.md#:~:text=Use%20descriptive%20commit%20messages%20%2D%20each%20commit%20should%20be%20small%20enough%20to%20describe%20it%20in%20one%20sentence.%20The%20commit%20message%20should%20be%20written%20in%20the%20imperative%20tense%20and%20capitalized)

Cheers and Happy coding!👏👏👏 💻  
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please ping me @BenMukebo when you comment so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-16 16:31 UTC, BenMukebo commented on README.md
> +
- [ ] Please update your Readme, currently some headings are missing such as  

``` ##  Getting Started ```

- [ ] It will be nice to add explicit steps to clone and run your project locally, as this will be of help to non-technical users.  This includes `git clone URL` , `cd project_name` etc

2022-08-16 16:31 UTC, BenMukebo commented on README.md
> +
- [ ]  I would also recommend adding the `Acknowledgments` section just after the Show your support section: 

```
## Show your support

Give a ⭐️ if you like this project!

## Acknowledgments

- Microverse
```


- please refer to this [template](https://github.com/microverseinc/readme-template), you can copy and paste the content but remember to customize it to your project.

2022-08-16 16:31 UTC, BenMukebo commented on index.html
> +    <link rel="stylesheet" href="style.css">
- [OPTIONAL] It always better to specify the path, sometimes it's can happen that your index file does not recognize where your CSS file is exactly located. In order to prevent that, you can add `./` before the CSS file name,  this should be like that:
 ` <link rel="stylesheet" href="./styles.css">`

2022-08-17 00:36 UTC, Reem-lab approved these changes
# Hi @ouasamine, 👋🏻👋🏻

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉🔥🔥💯💯
<img src="https://media1.giphy.com/media/BPJmthQ3YRwD6QqcVD/giphy.gif"/>


## Highlights ✨✨
📌 No Linters error ✅
📌 Descriptive pull request✅
📌 Great working on the functionality✅
📌 Good commit messages ✅
📌 Professional `README` file. ✅


## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-17 00:57 UTC, merged